name: Build MacOS Silicon
on: [push, workflow_dispatch]
jobs:
  build-macos-silicon:
    runs-on: macos-14
    steps:
      - name: "Verify that it's arm64 - a Silicon Mac"
        run: |
          sysctl -n machdep.cpu.brand_string
          uname -m
          uname -m | grep -q "arm64" || exit 1

      - name: Build the dependent libraries
        working-directory: /Users/runner/work
        run: |
          git clone https://github.com/SDL-Hercules-390/gists.git extpkgs
          cd extpkgs

          # Configure it for aarch64
          sed -i '' 's/^cpu .*/cpu = aarch64/' extpkgs.sh.ini

          ./extpkgs.sh clone c d s t

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure
        run: |
          ./configure --enable-extpkgs=/Users/runner/work/extpkgs/
      - name: Make
        run: |
          make
      - name: Make install
        run: |
          sudo make install
      - name: Check artifact
        run: hercules -v
