name: Build Ubuntu
on: [push, workflow_dispatch]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure
        run: |
          ./configure
      - name: Make
        run: |
          make
      - name: Make install
        run: |
          sudo make install
      - name: Check artifact
        run: hercules -v
