name: Build Windows
on: [push, workflow_dispatch]
jobs:
  "build-windows":
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Make
        run: |
          ./Makefile.bat RETAIL-X64
